try:
  num = (1/0)
except Exception as result:
    print(result)


print(num)